{
 "title": "Mysterium Network Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_total_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Public Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_public_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Quality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_avg_quality", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_avg_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Tbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysterium_total_bandwidth / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Public Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Tbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysterium_total_public_bandwidth / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_avg_bandwidth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Public Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_avg_public_bandwidth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Network Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MYST" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysterium_current_fee", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pricing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Residential VPN Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mysterium_residential_dvpn_gib", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Residential B2B VPN & Data Transfer Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysterium_residential_data_transfer_gib",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Residential Wireguard Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysterium_residential_wireguard_gib",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Residential B2B Data Scraping Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysterium_residential_scraping_gib",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other VPN Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mysterium_other_dvpn_gib", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Other B2B VPN & Data Transfer Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysterium_other_data_transfer_gib",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other Wireguard Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mysterium_other_wireguard_gib", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Other B2B Data Scraping Price",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MYST / GiB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mysterium_other_scraping_gib", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Top 10 Countries by Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "topk(10,\n  sum by(country) (\n    label_replace({__name__=~\"mysterium_bandwidth_.*\"}, \"country\", \"$1\", \"__name__\", \"mysterium_bandwidth_(.*)\")\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Bandwidth by Country",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by(country) (\n  label_replace({__name__=~\"mysterium_bandwidth_.*\"}, \"country\", \"$1\", \"__name__\", \"mysterium_bandwidth_(.*)\")\n) > 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "mysterium_total_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Public Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "mysterium_public_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Public Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Tbps" } },
   "targets": [
    {
     "expr": "mysterium_total_public_bandwidth / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Public Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "mysterium_avg_public_bandwidth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Quality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "mysterium_avg_quality", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Tbps" } },
   "targets": [
    {
     "expr": "mysterium_total_bandwidth / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "mysterium_avg_bandwidth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    { "expr": "mysterium_avg_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Network Fee",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "MYST" } },
   "targets": [
    { "expr": "mysterium_current_fee", "legendFormat": "__auto" }
   ]
  }
 ]
}